# .gitlab-ci.yml

stages:
  - debug

#
# Templates
#

.build:
  script:
    - CC=$CC meson build --buildtype debug
    - ninja -C ./build
    - ./build/loc src/*

.debug:
  stage: debug

.release:
  stage: release


#
# Jobs
#

Test clang + glibc:
  before_script:
    - apt update && apt upgrade -y
    - apt install -y clang lld meson
  extends:
    - .build
    - .debug
  image: ubuntu:20.04
  variables:
    CC: clang

Test gcc + glibc:
  before_script:
    - apt update && apt upgrade -y
    - apt install -y gcc meson
  extends:
    - .build
    - .debug
  image: ubuntu:20.04
  variables:
    CC: gcc

Test clang + musl:
  before_script:
    - apk --no-cache add clang gcc meson musl-dev
  extends:
    - .build
    - .debug
  image: alpine:edge
  variables:
    CC: clang

Test gcc + musl:
  before_script:
    - apk --no-cache add gcc meson musl-dev
  extends:
    - .build
    - .debug
  image: alpine:edge
  variables:
    CC: gcc
