# .gitlab-ci.yml

stages:
  - debug

#
# Templates
#

.debug:
  stage: debug
  script:
    - CC=$CC CC_LD=$LD meson build/debug --buildtype debug
    - ninja -C ./build/debug
    - ./build/debug/loc src/*

#
# Jobs
#

glibc-clang-lld:
  extends: .debug
  image: ubuntu:20.04
  variables:
    CC: clang
    LD: lld
  before_script:
    - apt update
    - apt install -y clang lld meson

glibc-gcc-bfd:
  extends: .debug
  image: ubuntu:20.04
  variables:
    CC: gcc
    LD: bfd
  before_script:
    - apt update
    - apt install -y gcc meson

musl-clang-lld:
  extends: .debug
  image: alpine:edge
  variables:
    CC: clang
    CC_LD: lld
  before_script:
    - apk --no-cache add clang gcc lld meson musl-dev

musl-gcc-bfd:
  extends: .debug
  image: alpine:edge
  variables:
    CC: gcc
    CC_LD: bfd
  before_script:
    - apk --no-cache add gcc meson musl-dev
